### ISSUE TITLE
Creating relationship between two models in rails

### ISSUE THREAD

**Issue by codemanimal** [codemanimal/Dealr#3]
Hey guys! Sorry for my absence. Turns out my flu was actually mono, so i've been working on the project from home. I'd really appreciate your thoughts on the following:

I am building a daily deals site and currently trying to add functionality such that a user can save a deal to his / her account and then go to their account to see the deals that they have saved. I'm using tunr and the relationship between playlists and songs as an example.

I have defined the many-to-many relationship in both the User and Deal models(classes?) and added 'add_deal' and 'remove_deal' methods to my User model (App/mdoels/user.rb). I've also added methods to the 'users_controller' and this is where my main issue lies. I would like to 'user.add_deal('deal that should be added'), but I cannot seem to select the current deal to pass it to the add_deal method. 

Please note 'views/deals/show.html.erb' --> this is where I have a link with id= 'save-deal-button' that should take me to the 'add_deal_to_user_path' via the 'user_controller.rb' which should save that deal to the current_user via 'user.add_deal(deal) and then redirect back to '/deals' or elsewhere.

@harimohanraj89 @DrRobotmck @bigtone1284 @WilliamfShaw 

Feel free to call me if you need further clarification. Latest version has been merged with master. THANKS!!!!!!

**Comment by DrRobotmck** [comment]
How can you get the id number for that particular deal to be passed along to your server? I see in your controller action that you've used `@deal` but you haven't defined it. It might make more sense to use the deals controller to add the deal, that way you can retrieve the id for that particular deal, and rely on `current_user` to access the user for whom you'd like to add the deal to.

**Comment by codemanimal** [comment]
Thanks, @DrRobotmck. That makes sense and is exactly what i'm in the process of trying. I was going to define a ```current_deal``` to access the deal within the ``UserController```, but had trouble with that, so will continue forward with your suggestion.
